### ISSUE TITLE
Support #rgb colors

### ISSUE THREAD

**Issue by asztalosdani** [Quick-Turn-Studio/CLionSupportForQt#52]
```css
QComboBox
{
    background-color: #ff0;
}
```
This works in Qt, but is highlighted as error.
![image](https://user-images.githubusercontent.com/9664767/143049741-ccec19f3-10a8-4780-9be2-76164d19fe55.png)
