### ISSUE TITLE
Support all named colors

### ISSUE THREAD

**Issue by asztalosdani** [Quick-Turn-Studio/CLionSupportForQt#53]
pink, fuchsia, lime, etc. are all highlighted as errors

**Comment by grabusr** [comment]
Hi @asztalosdani,

Could you tell what plugin gives you this error?

**Comment by asztalosdani** [comment]
Qt Style Sheet Highlighter
Example code:
```css
QWidget {
    background: pink;
}
```
