### ISSUE TITLE
Support camelcase functions

### ISSUE THREAD

**Issue by asztalosdani** [Quick-Turn-Studio/CLionSupportForQt#54]
E.g. QLinearGradient is marked as error

**Comment by grabusr** [comment]
Hi @asztalosdani,

Could you tell what plugin gives you this error? Can you also provide a code example and link to documentation that describe this feature?

**Comment by asztalosdani** [comment]
It's Qt Style Sheet Highlighter
Example code:
```css
QWidget {
    background: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 0.0 #121212, stop: 0.2 #282828, stop: 1 #484848);
}
```
![image](https://user-images.githubusercontent.com/9664767/149473686-50aac7e9-0a46-46b4-ab53-36d07c4a2ae8.png)

So the issue is, only the lowercase keyword is recognized, although both work in Qt.

**Comment by grabusr** [comment]
Hi @asztalosdani, could you provide a reference to that case insensitivity feature? We cannot find it in Qt documentation.

**Comment by asztalosdani** [comment]
Hi,

you can find it here: https://doc.qt.io/qt-5/stylesheet-syntax.html

> Qt Style Sheet is generally case insensitive (i.e., color, Color, COLOR, and cOloR refer to the same property). The only exceptions are class names, object names, and Qt property names, which are case sensitive.

Although QLinearGradient is a class name, I think the exception refers to the widget classes.
But this quote reveals that this should also work:
```css
QWidget {
    background: qlineargradient( X1: 0, y1: 0, x2: 1, y2: 0, STOP: 0.0 #121212, stop: 0.2 #282828, stop: 1 #484848);
}
```
![image](https://user-images.githubusercontent.com/9664767/149889720-8a9566c5-a9db-4582-b697-fab541f3eb14.png)
