### ISSUE TITLE
Feature: support preprocessed variables

### ISSUE THREAD

**Issue by tothambrus11** [Quick-Turn-Studio/CLionSupportForQt#59]
### Plugin

Qt Style Sheets Editor

### Feature description

It would be nice to have valid syntax highlighting for variables that are preprocessed by our program. These usually start with an @ symbol, but it could be a setting so others could define their owns (they might use a $ sign, idk).
There could be code completition for variable names after typing that special character.

The variable names could come from an editor settings option tracked by VCS, and could be extended using an alt+enter option when an unknown/new variable name is detected.

### Example

```css
FilterCheckbox {
    background: @backgroundColor;
}
``` 
```css
FilterCheckbox {
    background: $backgroundColor;
}
```
